version: '3.9'

services:
  db:
    image: postgres
    container_name: receipt_tracker_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: receipts
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
